DROP TABLE IF EXISTS places CASCADE;

CREATE TABLE places (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
img_url VARCHAR (255) NOT NULL,
comment VARCHAR (1500) NOT NULL
);

INSERT INTO places
  (name, img_url, comment)
VALUES
  ('Bali, Indonesia', 'http://i.imgur.com/7JZX6ZN.jpg', 'Bali takes you straight to the ‘can’t miss’ cultural treasures and famous landscapes found all around the magical island. There are innumerable temples, historical sites, and spots of natural beauty spread across eight regencies. Go east to see the majestic MOTHER TEMPLE of Besakih or travel to the heartland where rice paddies offer scenic photo opportunities. From scenic vistas to cultural performances, there is something for everyone.'),
  ('Barcelona, Spain', 'http://i.imgur.com/l8eRFkW.jpg', 'Inside this majestic Gothic quarter and architecture; then there''s the food and drink – the first-rate tapas bars, the abundant and inexpensive wine, the superb and reasonably priced multicourse lunches. Add Catalan creativity (Modernisme, Miró, Dalí), bohemian bars and stunning nearby getaways.Barcelona is, quite simply, one of the worlds most captivating cities.'),
  ('Bordeaux, France', 'http://i.imgur.com/9NSDOCp.jpg', 'They used to call her the ‘Sleeping Beauty’, but – though she’s hit the snooze button a few times – Bordeaux is now wide awake and ready for action. The new LGV Sud-Ouest line, due for completion in mid- 2017, connects the city with Europe’s high- speed train network and cuts travel time from Paris to just two hours. Its timing is perfect. The recently opened Cité du Vin continues the impressive redevelopment of the Garonne riverfront with a state-of-the-art wine-lovers’ experience, and the city’s gastronomic revolution keeps building on its own success. She’s going to skip breakfast: all aboard for Bordeaux’ grande bouffe!'),
  ('Cape, South Africa', 'http://i.imgur.com/1d70TFG.jpg', 'Cape Town’s deceptively laid-back folk have been working hard to add cultural and culinary cred to the Mother City’s famous natural charms, cementing its reputation as an African city with a global outlook. Local gastronomy is as impressive as Table Mountain’s flat-topped mass, with historic wine estates in every direction, hip markets selling the fruits of the Cape’s fertile terrain, and inventive restaurants winning global plaudits. The art and design scene will be given a boost in September by the opening of the Zeitz Museum of Contemporary Art Africa (MOCAA), the world’s largest museum of contemporary African art and a post-industrial architectural marvel occupying a century-old grain silo.'),
  ('Los Angeles, USA', 'http://i.imgur.com/S3qS82S.jpg', 'Despite its reputation as a land of celebrities, health fanatics and all-around superficiality, LA has been gaining steam as a cultural destination while becoming more accessible than ever. The 2016 Metro expansion has made getting from Downtown to Santa Monica and everywhere in between much easier; city initiative Car Free LA helps tourists navigate without wheels; and almost 50 new hotels are in the works. This isn’t just a beach town, either; it’s a commerce capital, where movie producers and finance types mingle over sashimi and kale salads. East Coasters are moving here in droves for the sunshine and a more sustainable lifestyle.'),
  ('Lisbon, Portugal', 'http://i.imgur.com/sUua4eP.jpg', 'It’s got sights, culture and cuisine, yet Lisbon’s rarely mentioned alongside southern European heavyweights such as Barcelona or Rome. If this mystifying lack of recognition is what helps the Portuguese capital remain a bargain, long may it continue. Add the weakness of the euro, and the city looks like an unbeatable deal. Should you need more persuasion, though, consider the museums: from Egyptian artefacts at Museu Calouste Gulbenkian to pop art at Museu Colecção Berardo, Lisbon groans with them, but the appetite appears unsated: a museum devoted to the history of Judaism in Portugal is coming to the Alfama district in 2017.'),
  ('Varadero, Cuba', 'http://i.imgur.com/t32ROav.jpg', 'Varadero, located on the sinuous 20km-long Hicacos peninsula, stands at the vanguard of Cuba’s most important industry – tourism. Uninterrupted 20km stretch of blond sand make this one, undoubtedly one of the Caribbeans best places to visit.'),
  ('Pistoia, Italy', 'http://i.imgur.com/BuCwbXn.jpg', 'People sometimes refer to Pistoia as ‘little Florence’ for its concentration of art and architecture. And yet, despite its charms, this Tuscan town sees just a fraction of Florence’s tourists. That’s set to change in 2017, when the city will take its turn as Italy’s Capital of Culture. Pistoia earned the title in recognition of its impressive cultural credentials and devotion to grass-roots ideas and local entrepreneurship. In return, the award offers the city an opportunity to showcase an alternative side to Tuscany: one that eschews grand-slam sights in favour of thriving small towns full of personality and dynamic, living culture.');
